#!/bin/bash

POSITIONAL_ARGS=()
START_TIME="09:00"
HOURS="8h"
LOCATION=""
YEAR=$(date +%Y)
MONTH=$(date +%m)
DAY=$(date +%d)
PROJECT=""
DYNAMIC_ARGS=""

while [[ $# -gt 0 ]]; do
  case $1 in
    -d|--day)
      DAY=`printf %02s $2`
      shift # past argument
      shift # past value
      ;;
    -md|--month-day)
      MONTH=`printf %02s $2`
      DAY=`printf %02s $3`
      shift # past argument
      shift # past month
      shift # past day
      ;;
    -ymd|--date)
      YEAR="$2"
      MONTH=`printf %02s $3`
      DAY=`printf %02s $4`
      shift # past argument
      shift # past year
      shift # past month
      shift # past day
      ;;
    -h|--half)
      HOURS="4h"
      shift # past argument
      ;;
    -p|--pm)
      START_TIME="14:00"
      shift # past argument
      ;;
    -o|--onsite)
      LOCATION="onsite"
      shift # past argument
      ;;
    -j|--project)
      PROJECT="$2"
      shift # past argument
      shift # past value
      ;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
    *)
      POSITIONAL_ARGS+=("$1") # save positional arg
      shift # past argument
      ;;
  esac
done

set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters

if [ -z "$1" ]; then DESCRIPTION="???"; else DESCRIPTION=$1; fi

if [ -n "$LOCATION" ]; then
  DYNAMIC_ARGS="--tags \"$LOCATION\""
fi

if [ -n "$PROJECT" ]; then
  DYNAMIC_ARGS="$DYNAMIC_ARGS --project \"$PROJECT\""
fi

# echo toggl add --billable $DYNAMIC_ARGS \"$YEAR.$MONTH.$DAY $START_TIME\" $HOURS \"$DESCRIPTION\"
# shellcheck disable=SC2086
eval toggl add --billable $DYNAMIC_ARGS \"$YEAR.$MONTH.$DAY $START_TIME\" $HOURS \"$DESCRIPTION\"